### ISSUE TITLE
[Question] PHP Version

### ISSUE THREAD

**Issue by TalkMarc** [Sylius/Sylius-Docker-Standard#33]
Please excuse the absolute noob question but i'm new to running stuff in containers:
How wold i go about changing the PHP version of the image from PHP 8.0 to 8.2 for development?

I see in #31 that the PHP version is in the Dockerfile so this means i gotta build the image myself and then use it in docker compose somehow?

**Comment by sabat24** [comment]
I needed to create a docker image with php 8.1 in order to write plugins for Sylius 1.13. If someone still needs it I pushed it to the docker hub under: `sabat24/sylius-standard:1.13-traditional-ubuntu`

There is no alpine version for now (which I prefer to use).

**Comment by TalkMarc** [comment]
Closing as this repo seems to be abandoned, with the container page even being annotated as "[ARCHIVED] DO NOT USE!" and being advised to use [this project](https://github.com/sylius/docker-images/pkgs/container/sylius-php) instead.

I personally solved my issue by writing a hacked together Docker and docker-compose file from the [sylius/sylius-standard one](https://github.com/Sylius/Sylius-Standard/blob/1.14/Dockerfile) to use with the [plugin skeleton](https://github.com/Sylius/PluginSkeleton) (which could also use some attention) for development. So the image for development purposes just gets build locally.
